# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: Imjlx
title: Imjlx

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Imjlx

description: Stylish Jekyll Theme
author:
  name: Imjlx
  # email: dbyll@ismaildemirbilek.com
  github: Imjlx
  # twitter: dbtek
  # pinterest: asd123
  # linkedin: asd123
  bio: 技术生活分享家
  email_md5: 

# rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: /assets/img/sidebar.png

BASE_PATH:

plugins:
  - jekyll-paginate
